export const ARTWORK_LIST_REQUEST = 'ARTWORK_LIST_REQUEST'; 
export const ARTWORK_LIST_SUCCESS = 'ARTWORK_LIST_SUCCESS';
export const ARTWORK_LIST_FAIL = 'ARTWORK_LIST_FAIL';
// ARTWORK DETAILS REQUESTS 


export const ARTWORK_DETAILS_REQUEST = 'ARTWORK_DETAILS_REQUEST'; 
export const ARTWORK_DETAILS_SUCCESS = 'ARTWORK_DETAILS_SUCCESS';
export const ARTWORK_DETAILS_FAIL = 'ARTWORK_DETAILS_FAIL';
// ARTWORK DELETE REQUESTS
export const ARTWORK_DELETE_REQUEST = 'ARTWORK_DELETE_REQUEST'; 
export const ARTWORK_DELETE_SUCCESS = 'ARTWORK_DELETE_SUCCESS';
export const ARTWORK_DELETE_FAIL = 'ARTWORK_DELETE_FAIL';
// ARTWORK CREATE REQUESTS

export const ARTWORK_CREATE_REQUEST = 'ARTWORK_CREATE_REQUEST'; 
export const ARTWORK_CREATE_SUCCESS = 'ARTWORK_CREATE_SUCCESS';
export const ARTWORK_CREATE_FAIL = 'ARTWORK_CREATE_FAIL';
export const ARTWORK_CREATE_RESET = 'ARTWORK_CREATE_RESET';
// ARTWORK UPDATE REQUESTS

export const ARTWORK_UPDATE_REQUEST = 'ARTWORK_UPDATE_REQUEST'; 
export const ARTWORK_UPDATE_SUCCESS = 'ARTWORK_UPDATE_SUCCESS';
export const ARTWORK_UPDATE_FAIL = 'ARTWORK_UPDATE_FAIL';
export const ARTWORK_UPDATE_RESET = 'ARTWORK_UPDATE_RESET';
// ARTWORK UPLOAD REQUESTS

export const ARTWORK_UPLOAD_REQUEST = 'ARTWORK_UPLOAD_REQUEST'; 
export const ARTWORK_UPLOAD_SUCCESS = 'ARTWORK_UPLOAD_SUCCESS';
export const ARTWORK_UPLOAD_FAIL = 'ARTWORK_UPLOAD_FAIL';
export const ARTWORK_UPLOAD_RESET = 'ARTWORK_UPLOAD_RESET';
// ARTWORK REVIEW REQUESTS

export const ARTWORK_REVIEW_REQUEST = 'ARTWORK_REVIEW_REQUEST'; 
export const ARTWORK_REVIEW_SUCCESS = 'ARTWORK_REVIEW_SUCCESS';
export const ARTWORK_REVIEW_FAIL = 'ARTWORK_REVIEW_FAIL';
export const ARTWORK_REVIEW_RESET = 'ARTWORK_REVIEW_RESET';
// ARTWORK TOP REQUESTS
export const ARTWORK_TOP_REQUEST = 'ARTWORK_TOP_REQUEST'; 
export const ARTWORK_TOP_SUCCESS = 'ARTWORK_TOP_SUCCESS';
export const ARTWORK_TOP_FAIL = 'ARTWORK_TOP_FAIL';
